MaxSpeed=         1000000
MaxSteering=      1200000
SensorRadius=     500
SensorSpan=       700
SensorMin=        80
MinDTicks=        10
MaxDTicks=        30000
DTicksBoost=      100000
ParamP1=          1000
ParamP2=          1
ParamPR=          4
ParamD1=          0
ParamD2=          0
ParamDR=          1
InnerBrakeFactor= 1
