MaxSpeed=         30

OutSteeringPC=    150
MaxSteeringPC=    120
MaxSlowPC=        60

SensorRadius=     100
SensorSpan=       700
SensorMin=        80
MinDTicks=        10
MaxDTicks=        30000
MinOutMillis=     10

KPn=              20
KPd=              1
KDn=              5
KDd=              1
KIn=              0
KId=              1
KIrn=             0
KIrd=             1
KELimitP=         280
KELimit=          2000
KEn=              0
KEd=              1
KErn=             0
KErd=             1

SlowStart1=       0
SlowEnd1=         0
SlowSpeed1=       0

SlowStart2=       0
SlowEnd2=         0
SlowSpeed2=       0

SlowStart3=       0
SlowEnd3=         0
SlowSpeed3=       0

SlowStart4=       0
SlowEnd4=         0
SlowSpeed4=       0

Timeout=          0
