MaxSpeed=         50
AccelPerTicksN=   5
AccelPerTicksD=   1

OutTimeMs=        500
OutPowerMax=      60
OutPowerMin=      30
OutPowerRn=       95
OutPowerRd=       100

MaxSteeringPC=    120
MaxSlowPC=        50

SensorHole=       40
SensorRadius=     100
SensorSpan=       700
SensorMin=        80
MinDTicks=        10
MaxDTicks=        30000
MinOutMillis=     10
DAvgMillis=       42
SpeedEstRn=       95
SpeedEstRd=       100

KPn=              20
KPd=              100
KDn=              2
KDd=              100
KIn=              0
KId=              1000
KIrn=             99
KIrd=             100
KEReduction=      180
KELimit=          5000
KEn=              10
KEd=              1
KErn=             99
KErd=             100

SlowStart1=       0
SlowEnd1=         0
SlowSpeed1=       0

SlowStart2=       0
SlowEnd2=         0
SlowSpeed2=       0

SlowStart3=       0
SlowEnd3=         0
SlowSpeed3=       0

SlowStart4=       0
SlowEnd4=         0
SlowSpeed4=       0

Timeout=          0
