MaxSpeed=         300000
MaxSteering=      120
SensorRadius=     500
SensorSpan=       700
SensorMin=        80
MinDTicks=        10
MaxDTicks=        30000
DTicksBoost=      100000
KP=               1000
KP2=              1
KPR=              4
KD=               0
KD2=              0
KDR=              1
KR=               1
