MaxSpeed=         50

OutInitMaxRn=     22
OutInitMaxRd=     100
OutPowerMax=      100
OutPowerMin=      30
OutPowerRn=       99
OutPowerRd=       100

MaxSteeringPC=    120
MaxSlowPC=        60

SensorHole=       40
SensorRadius=     100
SensorSpan=       700
SensorMin=        80
MinDTicks=        10
MaxDTicks=        30000
MinOutMillis=     10
DAvgMillis=       42
SpeedEstRn=       80
SpeedEstRd=       100


KPn=              1
KPd=              4
KDn=              1
KDd=              20
KIn=              0
KId=              1
KIrn=             90
KIrd=             100
KEReduction=      180
KELimit=          1
KEn=              0
KEd=              2
KErn=             90
KErd=             100

SlowStart1=       0
SlowEnd1=         0
SlowSpeed1=       0

SlowStart2=       0
SlowEnd2=         0
SlowSpeed2=       0

SlowStart3=       0
SlowEnd3=         0
SlowSpeed3=       0

SlowStart4=       0
SlowEnd4=         0
SlowSpeed4=       0

Timeout=          0
