MaxSpeed=         30
MaxSteeringPC=    120
SensorRadius=     100
SensorSpan=       700
SensorMin=        80
MinDTicks=        10
MaxDTicks=        30000
MinOutMillis=     10
KP=               70
KP2=              10
KD=               0
KD2=              0
